version: '3'
services:
    api:
        build: .
        container_name: tortoisetestcontainer
        ports:
            - 8000:80
        environment:
            - GUNICORN_CMD_ARGS="--reload"
        volumes:
            - ./app:/app