version: '3'
services:
    postgres:
        restart: on-failure
        image: postgres:10
        container_name: postgrescontainer
        ports:
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    api:
        build: .
        container_name: tortoisetestcontainer
        ports:
            - ${API_PORT}:80
        environment:
            - GUNICORN_CMD_ARGS="--reload"
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./app:/app
        depends_on:
            - postgres
volumes:
    postgres_data: